compose:
  '@itrocks/reflect:ReflectClass':    '@itrocks/framework:ReflectClass'
  '@itrocks/reflect:ReflectProperty': '@itrocks/framework:ReflectProperty'

server:
  host: 127.0.0.1
  port: 3000

session:
  path: /session
